name: "Behavior"

web: "[clientcide.com](http://clientcide.com)"

description: "Auto-instantiat widgets/classes based on parsed, declarative HTML with MooTools."

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "1.4.0"

sources:
  - "Source/Delegator.js"
  - "Source/Element.Data.js"
  - "Source/Event.Mock.js"
  - "Source/Behavior.js"
  - "Source/BehaviorAPI.js"
  - "Source/Behavior.Events.js"
  - "Source/Behavior.Startup.js"
  - "Source/Behavior.Trigger.js"
